// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUIIadWBkAOsOMpLJFuOkJMffUMxBSiY',
    appId: '1:454216249232:android:8b0073f5b15675076a8d15',
    messagingSenderId: '454216249232',
    projectId: 'flutter-delivery-app-e3cfd',
    storageBucket: 'flutter-delivery-app-e3cfd.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwg4hmgbfNTnSF5sgxecD_FmqPawXReY',
    appId: '1:454216249232:ios:eb01b95b644e6c2e6a8d15',
    messagingSenderId: '454216249232',
    projectId: 'flutter-delivery-app-e3cfd',
    storageBucket: 'flutter-delivery-app-e3cfd.appspot.com',
    iosClientId: '454216249232-jgnnar1d6nm7qmtig982aqb1gsj25i9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabProject',
  );
}
